name: Check and Test (PR)

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run type-checking
        run: npm run build:typecheck

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run E2E tests
        run: |
          npx playwright install
          npm run test:e2e